// Seti UI иконки для типов файлов.
// Источник: microsoft/vscode extensions/theme-seti (лицензия MIT).
// Глифы и цвета — из набора jesseweed/seti-ui (MIT), шрифт seti.woff.
// Сгенерировано из vs-seti-icon-theme.json (только тёмные варианты).

export const SETI_DEFS = new Map([
  ["_R", ["\uE001", "#519aba"]],
  ["_argdown", ["\uE003", "#519aba"]],
  ["_asm", ["\uE004", "#cc3e44"]],
  ["_audio", ["\uE005", "#a074c4"]],
  ["_babel", ["\uE006", "#cbcb41"]],
  ["_bazel", ["\uE007", "#8dc149"]],
  ["_bazel_1", ["\uE007", "#4d5a5e"]],
  ["_bicep", ["\uE008", "#519aba"]],
  ["_bower", ["\uE009", "#e37933"]],
  ["_bsl", ["\uE00A", "#cc3e44"]],
  ["_c", ["\uE00C", "#519aba"]],
  ["_c-sharp", ["\uE00B", "#519aba"]],
  ["_c_1", ["\uE00C", "#a074c4"]],
  ["_c_2", ["\uE00C", "#cbcb41"]],
  ["_cake", ["\uE00D", "#cc3e44"]],
  ["_cake_php", ["\uE00E", "#cc3e44"]],
  ["_clock", ["\uE012", "#519aba"]],
  ["_clock_1", ["\uE012", "#6d8086"]],
  ["_clojure", ["\uE013", "#8dc149"]],
  ["_clojure_1", ["\uE013", "#519aba"]],
  ["_code-climate", ["\uE014", "#8dc149"]],
  ["_code-search", ["\uE015", "#a074c4"]],
  ["_coffee", ["\uE016", "#cbcb41"]],
  ["_coldfusion", ["\uE018", "#519aba"]],
  ["_config", ["\uE019", "#6d8086"]],
  ["_cpp", ["\uE01A", "#519aba"]],
  ["_cpp_1", ["\uE01A", "#a074c4"]],
  ["_cpp_2", ["\uE01A", "#cbcb41"]],
  ["_crystal", ["\uE01B", "#d4d7d6"]],
  ["_crystal_embedded", ["\uE01C", "#d4d7d6"]],
  ["_css", ["\uE01D", "#519aba"]],
  ["_csv", ["\uE01E", "#8dc149"]],
  ["_cu", ["\uE01F", "#8dc149"]],
  ["_cu_1", ["\uE01F", "#a074c4"]],
  ["_d", ["\uE020", "#cc3e44"]],
  ["_dart", ["\uE021", "#519aba"]],
  ["_db", ["\uE022", "#f55385"]],
  ["_db_1", ["\uE022", "#519aba"]],
  ["_default", ["\uE023", "#d4d7d6"]],
  ["_docker", ["\uE025", "#519aba"]],
  ["_docker_1", ["\uE025", "#4d5a5e"]],
  ["_docker_2", ["\uE025", "#8dc149"]],
  ["_docker_3", ["\uE025", "#f55385"]],
  ["_ejs", ["\uE027", "#cbcb41"]],
  ["_elixir", ["\uE028", "#a074c4"]],
  ["_elixir_script", ["\uE029", "#a074c4"]],
  ["_elm", ["\uE02A", "#519aba"]],
  ["_eslint", ["\uE02C", "#a074c4"]],
  ["_eslint_1", ["\uE02C", "#4d5a5e"]],
  ["_ethereum", ["\uE02D", "#519aba"]],
  ["_f-sharp", ["\uE02E", "#519aba"]],
  ["_favicon", ["\uE02F", "#cbcb41"]],
  ["_firebase", ["\uE030", "#e37933"]],
  ["_firefox", ["\uE031", "#e37933"]],
  ["_font", ["\uE033", "#cc3e44"]],
  ["_git", ["\uE034", "#41535b"]],
  ["_github", ["\uE037", "#d4d7d6"]],
  ["_gitlab", ["\uE038", "#e37933"]],
  ["_go", ["\uE039", "#519aba"]],
  ["_go2", ["\uE03A", "#519aba"]],
  ["_godot", ["\uE03B", "#519aba"]],
  ["_godot_1", ["\uE03B", "#cc3e44"]],
  ["_godot_2", ["\uE03B", "#cbcb41"]],
  ["_godot_3", ["\uE03B", "#a074c4"]],
  ["_gradle", ["\uE03C", "#519aba"]],
  ["_grails", ["\uE03D", "#8dc149"]],
  ["_graphql", ["\uE03E", "#f55385"]],
  ["_grunt", ["\uE03F", "#e37933"]],
  ["_gulp", ["\uE040", "#cc3e44"]],
  ["_hacklang", ["\uE041", "#e37933"]],
  ["_haml", ["\uE042", "#cc3e44"]],
  ["_happenings", ["\uE043", "#519aba"]],
  ["_haskell", ["\uE044", "#a074c4"]],
  ["_haxe", ["\uE045", "#e37933"]],
  ["_haxe_1", ["\uE045", "#cbcb41"]],
  ["_haxe_2", ["\uE045", "#519aba"]],
  ["_haxe_3", ["\uE045", "#a074c4"]],
  ["_heroku", ["\uE046", "#a074c4"]],
  ["_hex", ["\uE047", "#cc3e44"]],
  ["_html", ["\uE048", "#519aba"]],
  ["_html_1", ["\uE048", "#8dc149"]],
  ["_html_2", ["\uE048", "#cbcb41"]],
  ["_html_3", ["\uE048", "#e37933"]],
  ["_html_erb", ["\uE049", "#cc3e44"]],
  ["_ignored", ["\uE04A", "#41535b"]],
  ["_illustrator", ["\uE04B", "#cbcb41"]],
  ["_image", ["\uE04C", "#a074c4"]],
  ["_info", ["\uE04D", "#519aba"]],
  ["_ionic", ["\uE04E", "#519aba"]],
  ["_jade", ["\uE04F", "#cc3e44"]],
  ["_java", ["\uE050", "#cc3e44"]],
  ["_java_1", ["\uE050", "#519aba"]],
  ["_javascript", ["\uE051", "#cbcb41"]],
  ["_javascript_1", ["\uE051", "#e37933"]],
  ["_javascript_2", ["\uE051", "#519aba"]],
  ["_jenkins", ["\uE052", "#cc3e44"]],
  ["_jinja", ["\uE053", "#cc3e44"]],
  ["_json", ["\uE055", "#cbcb41"]],
  ["_json_1", ["\uE055", "#8dc149"]],
  ["_julia", ["\uE056", "#a074c4"]],
  ["_karma", ["\uE057", "#8dc149"]],
  ["_kotlin", ["\uE058", "#e37933"]],
  ["_less", ["\uE059", "#519aba"]],
  ["_license", ["\uE05A", "#cbcb41"]],
  ["_license_1", ["\uE05A", "#e37933"]],
  ["_license_2", ["\uE05A", "#cc3e44"]],
  ["_liquid", ["\uE05B", "#8dc149"]],
  ["_livescript", ["\uE05C", "#519aba"]],
  ["_lock", ["\uE05D", "#8dc149"]],
  ["_lua", ["\uE05E", "#519aba"]],
  ["_makefile", ["\uE05F", "#e37933"]],
  ["_makefile_1", ["\uE05F", "#a074c4"]],
  ["_makefile_2", ["\uE05F", "#6d8086"]],
  ["_makefile_3", ["\uE05F", "#519aba"]],
  ["_markdown", ["\uE060", "#519aba"]],
  ["_maven", ["\uE061", "#cc3e44"]],
  ["_mdo", ["\uE062", "#cc3e44"]],
  ["_mustache", ["\uE063", "#e37933"]],
  ["_nim", ["\uE065", "#cbcb41"]],
  ["_notebook", ["\uE066", "#519aba"]],
  ["_npm", ["\uE067", "#41535b"]],
  ["_npm_1", ["\uE067", "#cc3e44"]],
  ["_npm_ignored", ["\uE068", "#41535b"]],
  ["_nunjucks", ["\uE069", "#8dc149"]],
  ["_ocaml", ["\uE06A", "#e37933"]],
  ["_odata", ["\uE06B", "#e37933"]],
  ["_pddl", ["\uE06C", "#a074c4"]],
  ["_pdf", ["\uE06D", "#cc3e44"]],
  ["_perl", ["\uE06E", "#519aba"]],
  ["_photoshop", ["\uE06F", "#519aba"]],
  ["_php", ["\uE070", "#a074c4"]],
  ["_pipeline", ["\uE071", "#e37933"]],
  ["_plan", ["\uE072", "#8dc149"]],
  ["_platformio", ["\uE073", "#e37933"]],
  ["_powershell", ["\uE074", "#519aba"]],
  ["_prisma", ["\uE075", "#519aba"]],
  ["_prolog", ["\uE077", "#e37933"]],
  ["_pug", ["\uE078", "#cc3e44"]],
  ["_puppet", ["\uE079", "#cbcb41"]],
  ["_purescript", ["\uE07A", "#d4d7d6"]],
  ["_python", ["\uE07B", "#519aba"]],
  ["_react", ["\uE07D", "#519aba"]],
  ["_react_1", ["\uE07D", "#e37933"]],
  ["_reasonml", ["\uE07E", "#cc3e44"]],
  ["_rescript", ["\uE07F", "#cc3e44"]],
  ["_rescript_1", ["\uE07F", "#f55385"]],
  ["_rollup", ["\uE080", "#cc3e44"]],
  ["_ruby", ["\uE081", "#cc3e44"]],
  ["_rust", ["\uE082", "#6d8086"]],
  ["_salesforce", ["\uE083", "#519aba"]],
  ["_sass", ["\uE084", "#f55385"]],
  ["_sbt", ["\uE085", "#519aba"]],
  ["_scala", ["\uE086", "#cc3e44"]],
  ["_shell", ["\uE089", "#8dc149"]],
  ["_slim", ["\uE08A", "#e37933"]],
  ["_smarty", ["\uE08B", "#cbcb41"]],
  ["_spring", ["\uE08C", "#8dc149"]],
  ["_stylelint", ["\uE08D", "#d4d7d6"]],
  ["_stylelint_1", ["\uE08D", "#4d5a5e"]],
  ["_stylus", ["\uE08E", "#8dc149"]],
  ["_sublime", ["\uE08F", "#e37933"]],
  ["_svelte", ["\uE090", "#cc3e44"]],
  ["_svg", ["\uE091", "#a074c4"]],
  ["_svg_1", ["\uE091", "#519aba"]],
  ["_swift", ["\uE092", "#e37933"]],
  ["_terraform", ["\uE093", "#a074c4"]],
  ["_tex", ["\uE094", "#519aba"]],
  ["_tex_1", ["\uE094", "#cbcb41"]],
  ["_tex_2", ["\uE094", "#e37933"]],
  ["_tex_3", ["\uE094", "#d4d7d6"]],
  ["_todo", ["\uE096"]],
  ["_tsconfig", ["\uE097", "#519aba"]],
  ["_twig", ["\uE098", "#8dc149"]],
  ["_typescript", ["\uE099", "#519aba"]],
  ["_typescript_1", ["\uE099", "#e37933"]],
  ["_vala", ["\uE09A", "#6d8086"]],
  ["_video", ["\uE09B", "#f55385"]],
  ["_vite", ["\uE09C", "#cbcb41"]],
  ["_vue", ["\uE09D", "#8dc149"]],
  ["_wasm", ["\uE09E", "#a074c4"]],
  ["_wat", ["\uE09F", "#a074c4"]],
  ["_webpack", ["\uE0A0", "#519aba"]],
  ["_wgt", ["\uE0A1", "#519aba"]],
  ["_windows", ["\uE0A2", "#519aba"]],
  ["_word", ["\uE0A3", "#519aba"]],
  ["_xls", ["\uE0A4", "#8dc149"]],
  ["_xml", ["\uE0A5", "#e37933"]],
  ["_yarn", ["\uE0A6", "#519aba"]],
  ["_yml", ["\uE0A7", "#a074c4"]],
  ["_zig", ["\uE0A8", "#e37933"]],
  ["_zip", ["\uE0A9", "#cc3e44"]],
  ["_zip_1", ["\uE0A9", "#6d8086"]],
]);

export const SETI_FILES = new Map([
  ["mix", "_hex"],
  ["karma.conf.js", "_karma"],
  ["karma.conf.cjs", "_karma"],
  ["karma.conf.mjs", "_karma"],
  ["karma.conf.coffee", "_karma"],
  ["readme.md", "_info"],
  ["readme.txt", "_info"],
  ["readme", "_info"],
  ["changelog.md", "_clock"],
  ["changelog.txt", "_clock"],
  ["changelog", "_clock"],
  ["changes.md", "_clock"],
  ["changes.txt", "_clock"],
  ["changes", "_clock"],
  ["version.md", "_clock"],
  ["version.txt", "_clock"],
  ["version", "_clock"],
  ["mvnw", "_maven"],
  ["pom.xml", "_maven"],
  ["tsconfig.json", "_tsconfig"],
  ["vite.config.js", "_vite"],
  ["vite.config.ts", "_vite"],
  ["vite.config.mjs", "_vite"],
  ["vite.config.mts", "_vite"],
  ["vite.config.cjs", "_vite"],
  ["vite.config.cts", "_vite"],
  ["swagger.json", "_json_1"],
  ["swagger.yml", "_json_1"],
  ["swagger.yaml", "_json_1"],
  ["mime.types", "_config"],
  ["jenkinsfile", "_jenkins"],
  ["babel.config.js", "_babel"],
  ["babel.config.json", "_babel"],
  ["babel.config.cjs", "_babel"],
  ["build", "_bazel"],
  ["build.bazel", "_bazel"],
  ["workspace", "_bazel"],
  ["workspace.bazel", "_bazel"],
  ["bower.json", "_bower"],
  ["docker-healthcheck", "_docker_2"],
  ["eslint.config.js", "_eslint"],
  ["firebase.json", "_firebase"],
  ["geckodriver", "_firefox"],
  ["gruntfile.js", "_grunt"],
  ["gruntfile.babel.js", "_grunt"],
  ["gruntfile.coffee", "_grunt"],
  ["gulpfile", "_gulp"],
  ["gulpfile.js", "_gulp"],
  ["ionic.config.json", "_ionic"],
  ["ionic.project", "_ionic"],
  ["platformio.ini", "_platformio"],
  ["rollup.config.js", "_rollup"],
  ["sass-lint.yml", "_sass"],
  ["stylelint.config.js", "_stylelint"],
  ["stylelint.config.cjs", "_stylelint"],
  ["stylelint.config.mjs", "_stylelint"],
  ["yarn.clean", "_yarn"],
  ["yarn.lock", "_yarn"],
  ["webpack.config.js", "_webpack"],
  ["webpack.config.cjs", "_webpack"],
  ["webpack.config.mjs", "_webpack"],
  ["webpack.config.ts", "_webpack"],
  ["webpack.config.build.js", "_webpack"],
  ["webpack.config.build.cjs", "_webpack"],
  ["webpack.config.build.mjs", "_webpack"],
  ["webpack.config.build.ts", "_webpack"],
  ["webpack.common.js", "_webpack"],
  ["webpack.common.cjs", "_webpack"],
  ["webpack.common.mjs", "_webpack"],
  ["webpack.common.ts", "_webpack"],
  ["webpack.dev.js", "_webpack"],
  ["webpack.dev.cjs", "_webpack"],
  ["webpack.dev.mjs", "_webpack"],
  ["webpack.dev.ts", "_webpack"],
  ["webpack.prod.js", "_webpack"],
  ["webpack.prod.cjs", "_webpack"],
  ["webpack.prod.mjs", "_webpack"],
  ["webpack.prod.ts", "_webpack"],
  ["license", "_license"],
  ["licence", "_license"],
  ["license.txt", "_license"],
  ["licence.txt", "_license"],
  ["license.md", "_license"],
  ["licence.md", "_license"],
  ["copying", "_license"],
  ["copying.txt", "_license"],
  ["copying.md", "_license"],
  ["compiling", "_license_1"],
  ["compiling.txt", "_license_1"],
  ["compiling.md", "_license_1"],
  ["contributing", "_license_2"],
  ["contributing.txt", "_license_2"],
  ["contributing.md", "_license_2"],
  ["qmakefile", "_makefile_1"],
  ["omakefile", "_makefile_2"],
  ["cmakelists.txt", "_makefile_3"],
  ["procfile", "_heroku"],
  ["todo", "_todo"],
  ["todo.txt", "_todo"],
  ["todo.md", "_todo"],
  ["npm-debug.log", "_npm_ignored"],
]);

export const SETI_EXT = new Map([
  ["bsl", "_bsl"],
  ["mdo", "_mdo"],
  ["cls", "_salesforce"],
  ["apex", "_salesforce"],
  ["asm", "_asm"],
  ["s", "_asm"],
  ["bicep", "_bicep"],
  ["bzl", "_bazel"],
  ["bazel", "_bazel"],
  ["build", "_bazel"],
  ["workspace", "_bazel"],
  ["bazelignore", "_bazel"],
  ["bazelversion", "_bazel"],
  ["h", "_c_1"],
  ["aspx", "_html"],
  ["ascx", "_html_1"],
  ["asax", "_html_2"],
  ["master", "_html_2"],
  ["hh", "_cpp_1"],
  ["hpp", "_cpp_1"],
  ["hxx", "_cpp_1"],
  ["h++", "_cpp_1"],
  ["edn", "_clojure_1"],
  ["cfc", "_coldfusion"],
  ["cfm", "_coldfusion"],
  ["litcoffee", "_coffee"],
  ["config", "_config"],
  ["cr", "_crystal"],
  ["ecr", "_crystal_embedded"],
  ["slang", "_crystal_embedded"],
  ["cson", "_json"],
  ["css", "_css"],
  ["css.map", "_css"],
  ["sss", "_css"],
  ["csv", "_csv"],
  ["xls", "_xls"],
  ["xlsx", "_xls"],
  ["cuh", "_cu_1"],
  ["hu", "_cu_1"],
  ["cake", "_cake"],
  ["ctp", "_cake_php"],
  ["d", "_d"],
  ["doc", "_word"],
  ["docx", "_word"],
  ["ejs", "_ejs"],
  ["ex", "_elixir"],
  ["exs", "_elixir_script"],
  ["elm", "_elm"],
  ["ico", "_favicon"],
  ["gitconfig", "_git"],
  ["gitkeep", "_git"],
  ["gitattributes", "_git"],
  ["gitmodules", "_git"],
  ["slide", "_go"],
  ["article", "_go"],
  ["gd", "_godot"],
  ["godot", "_godot_1"],
  ["tres", "_godot_2"],
  ["tscn", "_godot_3"],
  ["gradle", "_gradle"],
  ["gsp", "_grails"],
  ["gql", "_graphql"],
  ["graphql", "_graphql"],
  ["graphqls", "_graphql"],
  ["hack", "_hacklang"],
  ["haml", "_haml"],
  ["hs", "_haskell"],
  ["lhs", "_haskell"],
  ["hx", "_haxe"],
  ["hxs", "_haxe_1"],
  ["hxp", "_haxe_2"],
  ["hxml", "_haxe_3"],
  ["htm", "_html"],
  ["html", "_html"],
  ["jade", "_jade"],
  ["class", "_java_1"],
  ["classpath", "_java"],
  ["cjs", "_javascript"],
  ["js", "_javascript"],
  ["mjs", "_javascript"],
  ["js.map", "_javascript"],
  ["cjs.map", "_javascript"],
  ["mjs.map", "_javascript"],
  ["spec.js", "_javascript_1"],
  ["spec.cjs", "_javascript_1"],
  ["spec.mjs", "_javascript_1"],
  ["test.js", "_javascript_1"],
  ["test.cjs", "_javascript_1"],
  ["test.mjs", "_javascript_1"],
  ["es", "_javascript"],
  ["es5", "_javascript"],
  ["es7", "_javascript"],
  ["jinja", "_jinja"],
  ["jinja2", "_jinja"],
  ["kt", "_kotlin"],
  ["kts", "_kotlin"],
  ["liquid", "_liquid"],
  ["ls", "_livescript"],
  ["argdown", "_argdown"],
  ["ad", "_argdown"],
  ["mustache", "_mustache"],
  ["stache", "_mustache"],
  ["nim", "_nim"],
  ["nims", "_nim"],
  ["github-issues", "_github"],
  ["ipynb", "_notebook"],
  ["njk", "_nunjucks"],
  ["nunjucks", "_nunjucks"],
  ["nunjs", "_nunjucks"],
  ["nunj", "_nunjucks"],
  ["njs", "_nunjucks"],
  ["nj", "_nunjucks"],
  ["npm-debug.log", "_npm"],
  ["npmignore", "_npm_1"],
  ["npmrc", "_npm_1"],
  ["ml", "_ocaml"],
  ["mli", "_ocaml"],
  ["cmx", "_ocaml"],
  ["cmxa", "_ocaml"],
  ["odata", "_odata"],
  ["php.inc", "_php"],
  ["pipeline", "_pipeline"],
  ["pddl", "_pddl"],
  ["plan", "_plan"],
  ["happenings", "_happenings"],
  ["prisma", "_prisma"],
  ["pp", "_puppet"],
  ["epp", "_puppet"],
  ["purs", "_purescript"],
  ["spec.jsx", "_react_1"],
  ["test.jsx", "_react_1"],
  ["cjsx", "_react"],
  ["spec.tsx", "_react_1"],
  ["test.tsx", "_react_1"],
  ["re", "_reasonml"],
  ["res", "_rescript"],
  ["resi", "_rescript_1"],
  ["r", "_R"],
  ["rmd", "_R"],
  ["erb", "_html_erb"],
  ["erb.html", "_html_erb"],
  ["html.erb", "_html_erb"],
  ["sass", "_sass"],
  ["springbeans", "_spring"],
  ["slim", "_slim"],
  ["smarty.tpl", "_smarty"],
  ["tpl", "_smarty"],
  ["sbt", "_sbt"],
  ["scala", "_scala"],
  ["sol", "_ethereum"],
  ["styl", "_stylus"],
  ["svelte", "_svelte"],
  ["soql", "_db_1"],
  ["tf", "_terraform"],
  ["tf.json", "_terraform"],
  ["tfvars", "_terraform"],
  ["tfvars.json", "_terraform"],
  ["dtx", "_tex_2"],
  ["ins", "_tex_3"],
  ["toml", "_config"],
  ["twig", "_twig"],
  ["spec.ts", "_typescript_1"],
  ["test.ts", "_typescript_1"],
  ["text", "_default"],
  ["txt", "_default"],
  ["vala", "_vala"],
  ["vapi", "_vala"],
  ["component", "_html_3"],
  ["vue", "_vue"],
  ["wasm", "_wasm"],
  ["wat", "_wat"],
  ["pro", "_prolog"],
  ["zig", "_zig"],
  ["jar", "_zip"],
  ["zip", "_zip_1"],
  ["wgt", "_wgt"],
  ["ai", "_illustrator"],
  ["psd", "_photoshop"],
  ["pdf", "_pdf"],
  ["eot", "_font"],
  ["ttf", "_font"],
  ["woff", "_font"],
  ["woff2", "_font"],
  ["otf", "_font"],
  ["avif", "_image"],
  ["gif", "_image"],
  ["jpg", "_image"],
  ["jpeg", "_image"],
  ["png", "_image"],
  ["pxm", "_image"],
  ["svg", "_svg"],
  ["svgx", "_image"],
  ["tiff", "_image"],
  ["webp", "_image"],
  ["sublime-project", "_sublime"],
  ["sublime-workspace", "_sublime"],
  ["mov", "_video"],
  ["ogv", "_video"],
  ["webm", "_video"],
  ["avi", "_video"],
  ["mpg", "_video"],
  ["mp4", "_video"],
  ["mp3", "_audio"],
  ["ogg", "_audio"],
  ["wav", "_audio"],
  ["flac", "_audio"],
  ["3ds", "_svg_1"],
  ["3dm", "_svg_1"],
  ["stl", "_svg_1"],
  ["obj", "_svg_1"],
  ["dae", "_svg_1"],
  ["babelrc", "_babel"],
  ["babelrc.js", "_babel"],
  ["babelrc.cjs", "_babel"],
  ["bazelrc", "_bazel_1"],
  ["bowerrc", "_bower"],
  ["dockerignore", "_docker_1"],
  ["codeclimate.yml", "_code-climate"],
  ["eslintrc", "_eslint"],
  ["eslintrc.js", "_eslint"],
  ["eslintrc.cjs", "_eslint"],
  ["eslintrc.yaml", "_eslint"],
  ["eslintrc.yml", "_eslint"],
  ["eslintrc.json", "_eslint"],
  ["eslintignore", "_eslint_1"],
  ["firebaserc", "_firebase"],
  ["gitlab-ci.yml", "_gitlab"],
  ["jshintrc", "_javascript_2"],
  ["jscsrc", "_javascript_2"],
  ["stylelintrc", "_stylelint"],
  ["stylelintrc.json", "_stylelint"],
  ["stylelintrc.yaml", "_stylelint"],
  ["stylelintrc.yml", "_stylelint"],
  ["stylelintrc.js", "_stylelint"],
  ["stylelintignore", "_stylelint_1"],
  ["direnv", "_config"],
  ["static", "_config"],
  ["slugignore", "_config"],
  ["tmp", "_clock_1"],
  ["htaccess", "_config"],
  ["key", "_lock"],
  ["cert", "_lock"],
  ["cer", "_lock"],
  ["crt", "_lock"],
  ["pem", "_lock"],
  ["ds_store", "_ignored"],
  ["rs", "_rust"],
  ["ts", "_typescript"],
  ["tsx", "_react"],
  ["jsx", "_react"],
  ["py", "_python"],
  ["go", "_go2"],
  ["rb", "_ruby"],
  ["sh", "_shell"],
  ["bat", "_windows"],
  ["cmd", "_windows"],
  ["ps1", "_powershell"],
  ["cs", "_c-sharp"],
  ["fs", "_f-sharp"],
  ["fsx", "_f-sharp"],
  ["swift", "_swift"],
  ["dart", "_dart"],
  ["lua", "_lua"],
  ["sql", "_db"],
  ["php", "_php"],
  ["md", "_markdown"],
  ["yml", "_yml"],
  ["yaml", "_yml"],
  ["json", "_json"],
  ["jsonl", "_json"],
  ["env", "_config"],
  ["ini", "_config"],
  ["conf", "_config"],
  ["cfg", "_config"],
  ["gitignore", "_git"],
  ["lock", "_lock"],
  ["gz", "_zip_1"],
  ["tgz", "_zip_1"],
  ["tar", "_zip_1"],
  ["7z", "_zip_1"],
  ["rar", "_zip_1"],
  ["mkv", "_video"],
  ["ppt", "_word"],
  ["pptx", "_word"],
  ["c", "_c"],
  ["cc", "_cpp"],
  ["cxx", "_cpp"],
]);
